# Generated by Django 3.2.8 on 2021-11-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eqview', '0004_alter_equipment_borrowedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='borrowedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eqview.person'),
        ),
    ]
