# Generated by Django 3.2.8 on 2021-11-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateTimeField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
