# Generated by Django 3.2.8 on 2021-11-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_auto_20211117_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.DateTimeField(max_length=100),
        ),
    ]
