# Generated by Django 3.2.8 on 2021-11-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20211117_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
