# Generated by Django 3.2.8 on 2021-10-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqview', '0002_alter_equipment_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='question',
            new_name='borrowedBy',
        ),
    ]
