# Generated by Django 3.2.8 on 2021-11-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqview', '0006_alter_equipment_borrowedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serialNum',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
