# Generated by Django 3.2.8 on 2021-10-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eqview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eqview.person'),
        ),
    ]
