# Generated by Django 3.2.8 on 2021-10-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eqview', '0003_rename_question_equipment_borrowedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='borrowedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eqview.person'),
        ),
    ]
